Repository ssec-jhu/evolver-ng, pull requests merged in 2024-07, with the labels that each got.

#96 LED driver
  evolver/hardware/standard/led.py
  evolver/hardware/standard/tests/test_standard.py
Labels: new feature

#88 Load config from file using model_validate
  evolver/base.py
  evolver/tests/test_base.py
Labels: new feature

#98 Dedupe accidental line copy
  evolver/base.py
Labels: bug, fix

#99 Only shallow model dump from ConfigDescriptor.create to keep nested descriptors as instances and not dicts
  evolver/base.py
  evolver/serial.py
  evolver/tests/test_base.py
Labels: bug, fix

#100 pump and stir
  evolver/hardware/standard/pump.py
  evolver/hardware/standard/stir.py
  evolver/hardware/standard/tests/test_standard.py
  evolver/hardware/test_utils.py
Labels: enhancement

#105 104 Fix container-config inheritance mismatch
  evolver/connection/interface.py
  evolver/controller/interface.py
  evolver/controller/standard/chemostat.py
  evolver/device.py
  evolver/hardware/demo.py
  evolver/hardware/interface.py
  evolver/hardware/standard/led.py
  evolver/hardware/standard/od_sensor.py
  evolver/hardware/standard/pump.py
  evolver/hardware/standard/stir.py
  evolver/hardware/standard/temperature.py
  evolver/history.py
  evolver/serial.py
  evolver/tests/test_base.py
Labels: bug, fix
